# in mongodb deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: bimal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: "myDatabase"            # Change this if necessary

        volumeMounts:               # mounting to container
          - name: mongo-volume      # can be any name
            mountPath: /data/db     # MongoDB default data directory

      volumes:                      # need storage from PVC
        - name: mongo-volume        # same name as in volumeMounts
          persistentVolumeClaim:
            claimName: bimal-pvc    # same pvc name as in pvc.yml
