apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: bimal-pvc
  namespace: bimal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: bimal-sc      # same storage name as in storage.yml
